name: fetchUrl hash updater

on:
  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "experimental-features = nix-command flakes"
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install packages
        run: nix-env -i jq nixpkgs-fmt -f '<nixpkgs>'
      - name: Check gui hashes
        run: |
          export CURRENT_HASH=$(cat pkgs/gui-client.nix | grep  'hash = ".*";')
          export NEW_HASH="hash = $(nix store prefetch-file https://www.virtualhere.com/sites/default/files/usbclient/vhuit64 --json | jq .hash);"

          if [ "$NEW_HASH" != "$CURRENT_HASH" ]; then
            sed -i "s,$CURRENT_HASH,$NEW_HASH," pkgs/gui-client.nix
            nixpkgs-fmt .
          fi
      - uses: EndBug/add-and-commit@v9
        with:
            default_author: github_actions
            message: "Updated vhuit64 file hash"

      - name: Check cli hashes
        run: |
          export CURRENT_HASH=$(cat pkgs/cli-client.nix | grep  'hash = ".*";')
          export NEW_HASH="hash = $(nix store prefetch-file https://www.virtualhere.com/sites/default/files/usbclient/vhclientx86_64 --json | jq .hash);"

          if [ "$NEW_HASH" != "$CURRENT_HASH" ]; then
            sed -i "s,$CURRENT_HASH,$NEW_HASH," pkgs/cli-client.nix
            nixpkgs-fmt .
          fi
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated vhclientx86_64 file hash"